stages:
  - ci

variables:
  # Makes some things print in color
  TERM: ansi

before_script:
  # Enable nix-command and flakes
  - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf

  # Add nix-community binary cache
  - echo "extra-substituters = https://nix-community.cachix.org" >> /etc/nix/nix.conf
  - echo "extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=" >> /etc/nix/nix.conf

  # Install direnv and nix-direnv
  - nix-env -iA nixpkgs.direnv nixpkgs.nix-direnv

  # Allow .envrc
  - direnv allow

  # Set CARGO_HOME to a cacheable path
  - export CARGO_HOME="$(git rev-parse --show-toplevel)/.gitlab-ci.d/cargo"

ci:
  stage: ci
  image: nixos/nix:2.19.2
  script:
    - direnv exec . engage
  cache:
    paths:
      - target
      - .gitlab-ci.d
